/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Eye.gltf --transform
Author: niver_mk (https://sketchfab.com/niver_mk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eye-implant-e988ba5725fe4111b82f945a068c7c81
Title: Eye Implant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Eye-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.53, -11.65, 0]} rotation={[-Math.PI / 2, 0.09, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.eye_eye_material_0.geometry} material={materials.eye_material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.sclera_sclera_material_0.geometry} material={materials.sclera_material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Eye-transformed.glb')
