/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Neuron.gltf --transform
Author: Swarmrider (https://sketchfab.com/Swarmrider)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/singularity-001-e392fc2d7d61449b9b20bfb997171b7b
Title: Singularity 001
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Neuron-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Toon_geo_Toon_0.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0_1.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0_2.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0_3.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0_4.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0_5.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Toon_geo_Toon_0_6.geometry} material={materials.Toon} />
      <mesh geometry={nodes.Electricity_geo_Electricity_0.geometry} material={materials.Electricity} />
      <mesh geometry={nodes.NeonPulse_geo_NeonPulse_0.geometry} material={materials.Electricity} />
      <mesh geometry={nodes.Light_geo_Light_0.geometry} material={materials.Light} />
    </group>
  )
}

useGLTF.preload('/Neuron-transformed.glb')
