/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 robot.gltf --transform
Author: BumblBean (https://sketchfab.com/BumblBean)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-52901926700e49a394d6f59b39b15c32
Title: Robot
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/robot-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() =>{
    actions.Robot.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="2a6be7708a9a46d5b163d76c3305b20afbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="locator1" position={[416.63, 115.16, 340.24]} rotation={[-1.05, Math.PI / 10, 2.63]} />
                <group name="Fragel" position={[-663.45, 307.18, -115.05]} rotation={[-1.59, 0.01, -1.76]} scale={52.44}>
                  <mesh name="Fragel_Red_0" geometry={nodes.Fragel_Red_0.geometry} material={materials.material} />
                </group>
                <group name="Heavy" position={[376.16, 26.51, 288.96]} rotation={[0.03, 0.86, 1.58]} scale={53}>
                  <mesh name="Heavy_blinn3_0" geometry={nodes.Heavy_blinn3_0.geometry} material={materials.blinn3} />
                </group>
                <group name="locator2" position={[416.63, 115.16, 340.24]} rotation={[-2.11, -0.98, 2.17]} />
                <group name="Robot_Arm_Strong_Rig">
                  <group name="Controls">
                    <group name="Ctrl_Global_Move_Scale">
                      <group name="Ctrls_Upper" position={[75.47, 355.84, 77.75]} rotation={[0.01, -0.79, -0.38]}>
                        <group name="CTRL_FK_Upper_os_GRP" position={[95.68, 4.16, 0.31]} rotation={[3.14, 0, 1.59]}>
                          <group name="CTRL_FK_Upper" rotation={[0, 0, -1.38]}>
                            <group name="CTRL_Claw_Main_Rotate_os_GRP" position={[217.59, 32.8, 0.44]} rotation={[3.14, 0, 1.57]}>
                              <group name="CTRL_Claw_Main_Rotate">
                                <group name="CTRL_Claw_Ball_Rotate_os_GRP" position={[42.39, -45.73, 0]} rotation={[Math.PI, 0, 1.57]}>
                                  <group name="CTRL_Claw_Ball_Rotate" rotation={[0.11, 0, 0]}>
                                    <group name="CTRL_Claw_R_os_GRP" position={[-0.35, -0.4, -3.54]} rotation={[-1.57, 0, 0.85]}>
                                      <group name="CTRL_Claw_R" rotation={[0, 0, 0.2]} />
                                    </group>
                                    <group name="CTRL_Claw_L_os_GRP" position={[-0.35, -0.38, 3.55]} rotation={[1.57, 0, -2.29]}>
                                      <group name="CTRL_Claw_R1" rotation={[0, 0, 0.2]} />
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group name="CTRL_Base_Rotate_os_GRP" position={[0, 80.76, 0]} rotation={[0, 0, Math.PI / 2]}>
                        <group name="CTRL_Base_Rotate" rotation={[-0.06, 0, 0]}>
                          <group name="CTRL_FK_Base_Pivot_os_GRP" position={[63.51, 0, 0]} rotation={[0, -0.01, 0]}>
                            <group name="CTRL_FK_Base_Pivot">
                              <group name="CTRL_FK_Elboq_os_GRP" position={[313.05, 0, 0]} rotation={[-1.57, 0, -1.54]} />
                            </group>
                          </group>
                          <group name="IK_Controls_Base_Offset">
                            <group name="CTRL_IK_Translate_os_GRP" position={[376.63, 0, 223.41]} rotation={[-1.57, 0, -1.55]}>
                              <group name="CTRL_IK_Translate" position={[-152.69, -98.63, -80.08]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="DO_NOT_TOUCH">
                    <group name="Skeleton">
                      <group name="Object_32">
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Robot_Armstrong} skeleton={nodes.Object_56.skeleton} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Base" position={[356.57, -14, 257.41]} rotation={[0, 0.87, 0]} scale={[223.3, 18.85, 238.19]}>
                  <mesh name="Base_lambert1_0" geometry={nodes.Base_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="Shelf" position={[-614.62, 300.8, -41.34]}>
                  <group name="pCube4" position={[-162.78, 0, 299.24]} scale={[16.19, 606.79, 16.19]}>
                    <mesh name="pCube4_lambert1_0" geometry={nodes.pCube4_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="pCube3" position={[-276.23, 0, 146.13]} scale={[16.19, 606.79, 16.19]}>
                    <mesh name="pCube3_lambert1_0" geometry={nodes.pCube3_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="pCube2" position={[127.51, 0, -259.62]} scale={[16.19, 606.79, 16.19]}>
                    <mesh name="pCube2_lambert1_0" geometry={nodes.pCube2_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="pCube1" position={[265.85, 0, -115.39]} scale={[16.19, 606.79, 16.19]}>
                    <mesh name="pCube1_lambert1_0" geometry={nodes.pCube1_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="Boards1" position={[0, -37.11, -4.84]} rotation={[0, 0.78, 0]} scale={[650.3, 34.38, 206.3]}>
                    <mesh name="Boards1_Brown_0" geometry={nodes.Boards1_Brown_0.geometry} material={materials.Brown} />
                  </group>
                  <group name="Boards" position={[0, 155, -4.84]} rotation={[0, 0.78, 0]} scale={[650.3, 34.38, 206.3]}>
                    <mesh name="Boards_Brown_0" geometry={nodes.Boards_Brown_0.geometry} material={materials.Brown} />
                  </group>
                </group>
                <group name="BottomShelf">
                  <group name="Shard1" position={[-614.62, 77.22, -46.19]} rotation={[0, 0.78, 0]} scale={[650.3, 34.38, 206.3]}>
                    <mesh name="Shard1_Brown_0" geometry={nodes.Shard1_Brown_0.geometry} material={materials.Brown} />
                  </group>
                  <group name="ShardRight" position={[-614.62, 77.22, -46.19]} rotation={[0, 0.78, 0]} scale={[650.3, 34.38, 206.3]}>
                    <mesh name="ShardRight_Brown_0" geometry={nodes.ShardRight_Brown_0.geometry} material={materials.Brown} />
                  </group>
                  <group name="ShardLeft1" position={[-614.62, 77.22, -46.19]} rotation={[0, 0.78, 0]} scale={[650.3, 34.38, 206.3]}>
                    <mesh name="ShardLeft1_Brown_0" geometry={nodes.ShardLeft1_Brown_0.geometry} material={materials.Brown} />
                  </group>
                  <group name="Left" position={[-614.62, 77.22, -46.19]} rotation={[0, 0.78, 0]} scale={[650.3, 34.38, 206.3]}>
                    <mesh name="Left_Brown_0" geometry={nodes.Left_Brown_0.geometry} material={materials.Brown} />
                  </group>
                  <group name="Right" position={[-614.62, 77.22, -46.19]} rotation={[0, 0.78, 0]} scale={[650.3, 34.38, 206.3]}>
                    <mesh name="Right_Brown_0" geometry={nodes.Right_Brown_0.geometry} material={materials.Brown} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robot-transformed.glb')
